---
title: Sense HAT lukraak knipperen
hero_image: images/cover.png
description: Laat je Sense HAT stralen
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Inleiding
-
title: Wat heb je nodig
-
title: Het gebruik van set_pixel
-
title: De module random gebruiken
-
title: Voeg een lus toe