---
title: Sense HAT lukraak knipperen
hero_image: images/cover.png
description: Laat je Sense HAT stralen
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Het gebruik van set_pixel
  - 
    title: De module random gebruiken
