---
title: Sense HAT lukraak knipperen
hero_image: afbeeldingen/omslag
description: Laat je Sense HAT stralen
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: ""
technologies: "sense-hat, python"
site_areas: ""
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Het gebruik van set_pixel
  - 
    title: De module random gebruiken
  - 
    title: Voeg een lus toe
