---
title: Sense HAT lukraak knipperen
hero_image: afbeeldingen / banner.png
description: Laat je Sense HAT stralen
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmeren-0, computeren-0
interests: ""
technologies: "sense-hat, python"
site_areas: ""
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: Het gebruik van set_pixel
  - 
    title: De module random gebruiken
  - 
    title: Voeg een lus toe
