title: Sense HAT Random Sparkles
hero_image: images/cover.png
description: Make your Sense HAT shine with pride
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Using set_pixel
- title: Using the random module
- title: Add a loop