title: Sense HAT Random Sparkles
hero_image: images/cover.png
description: Make your Sense HAT shine with pride
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests:
technologies: "sense-hat, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Using set_pixel
  - title: Using the random module
  - title: Add a loop
