---
title: Sense HAT की यादृच्छिक चमक
hero_image: images/cover.png
description: गर्व के साथ अपने Sense HAT को चमकाए
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: परिचय
  - 
    title: Using set_pixel
  - 
    title: Using the random module
  - 
    title: Add a loop
