---
title: Sense HAT Random Sparkles
hero_image: images/cover.png
description: あなたのセンスHATをプライドで輝かせる
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: はじめに
  - 
    title: 必要なもの
  - 
    title: set_pixelの使用
  - 
    title: 乱数モジュールの使用
