---
title: Sense HAT Véletlenszerű Sparkles
hero_image: images / banner.png
description: Tegye meg a Sense HAT büszkeségét
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programozás-0, fizikai-comp-0
interests: ""
technologies: "sense-kalap, python"
site_areas: ""
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: A set_pixel használata
  - 
    title: Véletlenszerű modul használata
  - 
    title: Hurok hozzáadása
