---
title: Случайно HAT случайни искри
hero_image: images/cover.png
description: Направете си чувство HAT блясък с гордост
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Въведение
  - 
    title: Using set_pixel
  - 
    title: Using the random module
  - 
    title: Add a loop
