---
title: Zufälliges Funkeln mit Sense HAT
hero_image: images/cover.png
description: Lassen Sie Ihren Sense HAT mit Stolz erstrahlen
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Einleitung
  - 
    title: set_pixel verwenden
  - 
    title: Das random-Modul (Zufallsmodul) verwenden
  - 
    title: Füge eine Schleife hinzu
