---
title: Zufälliges Funkeln mit Sense HAT
hero_image: images/cover.png
description: Lassen Sie Ihren Sense HAT mit Stolz erstrahlen
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Einleitung
-
title: Was wirst du brauchen
-
title: Verwenden von set_pixel
-
title: Das Zufallsmodul verwenden
-
title: Eine Schleife hinzufügen