---
title: Sense HAT Véletlenszerű Szikrák
hero_image: images/cover.png
description: Tedd büszkén ragyogová a Sence HAT -et
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Using set_pixel
  - 
    title: Using the random module
  - 
    title: Add a loop
