---
title: Sense HAT véletlenszerű szikrák
hero_image: images/cover.png
description: Tedd büszkén ragyogóvá a Sense HAT-et
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: A set_pixel függvény használata
  - 
    title: A véletlenszám-generáló modul használata
  - 
    title: Adj hozzá egy ciklust
