---
title: Sense HAT Véletlenszerű Szikrák
hero_image: images / banner.png
description: Tedd büszkén ragyogová a Sence HAT -et
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Bevezetés
-
title: Amire szükséged lesz
-
title: A set_pixel használata
-
title: Véletlenszerű modul használata
-
title: Hurok hozzáadása