---
title: Sense HAT Véletlenszerű Szikrák
hero_image: images/cover.png
description: Tedd büszkén ragyogová a Sence HAT -et
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programozás-0, fizikai-comp-0
interests: ""
technologies: "sense-kapap, python"
site_areas: ""
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: A set_pixel használata
  - 
    title: Véletlenszerű modul használata
  - 
    title: Hurok hozzáadása
