---
title: Sense HAT Random Sparkles
hero_image: images/banner.png
description: Make your Sense HAT shine with pride
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: ""
technologies: "sense-hat, python"
site_areas: ""
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: Using set_pixel
  - 
    title: Using the random module
  - 
    title: Add a loop
