---
title: Scintillements aléatoires Sense HAT
hero_image: images/cover.png
description: Faites briller votre Sense HAT avec fierté
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Utiliser set_pixel
  - 
    title: Utiliser le module aléatoire
  - 
    title: Ajouter une boucle
