---
title: Destellos aleatorios con Sense HAT
hero_image: images/cover.png
description: Haz que tu Sense HAT brille con orgullo
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
- title: Introducción
  completion: engaged
- title: Usando set_pixel
- title: Usando el módulo random
  completion: internal
- title: Añade un bucle
