---
title: Étincelles aléatoires sur Sense HAT
hero_image: images/cover.png
description: Faites briller votre Sense HAT avec fierté
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Utiliser set_pixel
  - 
    title: Utiliser le module aléatoire
