---
title: Étincelles aléatoires sur Sense HAT
hero_image: images/cover.png
description: Faites briller votre Sense HAT avec fierté
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Ce dont vous aurez besoin
- title: Utiliser set_pixel
  completion: internal
- title: Utiliser le module aléatoire
- title: Ajouter une boucle
