---
title: Scintillii con il Sense HAT
hero_image: images/cover.png
description: Fai risplendere d'orgoglio il tuo Sense Hat
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: art
technologies: sense-hat, python
site_areas: jam
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduzione
- title: Di cosa avrai bisogno
- title: Usare set_pixel
- title: Utilizzare il modulo random
- title: Aggiungi un ciclo