---
title: Scintillii con il Sense HAT
hero_image: images/cover.png
description: Fai risplendere d'orgoglio il tuo Sense Hat
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Usare set_pixel
  - 
    title: Utilizzare il modulo random
