---
title: Scintillii con il Sense HAT
hero_image: images / banner.png
description: Fai splendere il Sense HAT con orgoglio
theme: rosso
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: ""
technologies: "sense-hat, python"
site_areas: ""
steps:
  - 
    title: introduzione
  - 
    title: Cosa ti serve
  - 
    title: Uso di set_pixel
  - 
    title: Uso del modulo random
  - 
    title: Aggiungi un ciclo
